/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: [
    './src/**/*.{html,js,ts,jsx,tsx}',
    './index.html',
  ],
  theme: {
    extend: {
      colors: {
        'on-error-container': '#93000a',
        'outline': '#747878',
        'on-tertiary-container': '#838484',
        'tertiary-fixed': '#e2e2e2',
        'surface-container-high': '#e9e8e7',
        'surface-container': '#efeded',
        'on-primary-container': '#858383',
        'primary': '#000000',
        'on-tertiary-fixed': '#1a1c1c',
        'primary-fixed-dim': '#c8c6c5',
        'on-error': '#ffffff',
        'on-surface': '#1b1c1c',
        'secondary-fixed': '#ffdad6',
        'error-container': '#ffdad6',
        'secondary': '#b6181f',
        'primary-fixed': '#e5e2e1',
        'on-background': '#1b1c1c',
        'on-primary': '#ffffff',
        'secondary-fixed-dim': '#ffb3ac',
        'tertiary': '#000000',
        'on-tertiary-fixed-variant': '#454747',
        'surface-container-highest': '#e4e2e2',
        'inverse-surface': '#303031',
        'surface': '#fbf9f8',
        'on-secondary-fixed-variant': '#930010',
        'surface-bright': '#fbf9f8',
        'on-surface-variant': '#444748',
        'on-primary-fixed-variant': '#474746',
        'on-secondary-container': '#fffbff',
        'on-tertiary': '#ffffff',
        'background': '#fbf9f8',
        'on-secondary-fixed': '#410003',
        'error': '#ba1a1a',
        'on-secondary': '#ffffff',
        'tertiary-container': '#1a1c1c',
        'tertiary-fixed-dim': '#c6c6c7',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f5f3f3',
        'surface-tint': '#5f5e5e',
        'on-primary-fixed': '#1c1b1b',
        'inverse-on-surface': '#f2f0f0',
        'surface-dim': '#dbdad9',
        'primary-container': '#1c1b1b',
        'surface-variant': '#e4e2e2',
        'secondary-container': '#d93534',
        'inverse-primary': '#c8c6c5',
        'outline-variant': '#c4c7c7',
        'heritage-red': '#b6181f',
        'champagne-gold': '#858383',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        'margin-mobile': '20px',
        gutter: '24px',
        'unit-lg': '32px',
        'unit-xl': '64px',
        'unit-md': '16px',
        'unit-xs': '4px',
        'container-max': '1280px',
        'unit-sm': '8px',
        'margin-desktop': '64px',
        'section-gap-desktop': '120px',
        'section-gap-mobile': '64px',
      },
      maxWidth: {
        container: '1280px',
      },
      fontFamily: {
        'headline-lg-mobile': ['Playfair Display', 'serif'],
        'headline-lg': ['Playfair Display', 'serif'],
        'headline-md': ['Playfair Display', 'serif'],
        'headline-md-mobile': ['Playfair Display', 'serif'],
        'body-md': ['Hanken Grotesk', 'sans-serif'],
        'body-lg': ['Hanken Grotesk', 'sans-serif'],
        'label-sm': ['Hanken Grotesk', 'sans-serif'],
        'headline-xl': ['Playfair Display', 'serif'],
        'label-md': ['Hanken Grotesk', 'sans-serif'],
        'display-hero': ['Playfair Display', 'serif'],
        metadata: ['Hanken Grotesk', 'sans-serif'],
        'label-caps': ['Hanken Grotesk', 'sans-serif'],
      },
      fontSize: {
        'headline-lg-mobile': ['32px', { lineHeight: '40px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'headline-lg': ['40px', { lineHeight: '48px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'headline-md': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'headline-md-mobile': ['20px', { lineHeight: '28px', fontWeight: '600' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'label-sm': ['12px', { lineHeight: '16px', letterSpacing: '0.03em', fontWeight: '500' }],
        'headline-xl': ['64px', { lineHeight: '72px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'label-md': ['14px', { lineHeight: '20px', letterSpacing: '0.05em', fontWeight: '600' }],
        'display-hero': ['72px', { lineHeight: '1.1', letterSpacing: '-0.02em', fontWeight: '700' }],
        'display-hero-mobile': ['40px', { lineHeight: '1.2', letterSpacing: '-0.01em', fontWeight: '700' }],
        'label-caps': ['12px', { lineHeight: '1.5', letterSpacing: '0.15em', fontWeight: '600' }],
        metadata: ['14px', { lineHeight: '1.4', fontWeight: '500' }],
      },
    },
  },
  plugins: [],
};
